import { formatTimeFromSeconds, standardDistances } from './utils';
import { secondsFromFields, type TimeFields } from './forms';
import tables from './predictorTables.json';

/**
 * Race Time Predictor v2: the evidence model (17 Sep 2026).
 *
 * Every number comes from predictorTables.json, generated by
 * filmmyrun-ios/tools/ultra-calibration/export_predictor.py from 2.37M UK
 * road performances (Power of 10, 2021–25), 318k UK ultra finishes (DUV,
 * 2015–26) and 25k runners with both. Design and evidence:
 * filmmyrun-ios/docs/superpowers/specs/2026-09-17-evidence-predictor-design.md
 * and tools/ultra-calibration/REPORT.md.
 *
 * Up to the marathon: T2 = T1 × (D2/D1)^k, with k looked up by the pair of
 * distances and the known time (and sex where the data shows a difference).
 * Beyond the marathon: ln T = ability + race cost, ability from the
 * (marathon-equivalent) known time, cost from the race itself when we have
 * measured it, otherwise from distance, climb and surface.
 *
 * The iOS app ports this file line for line (FMRCore/Calculators/RacePredictor.swift);
 * keep the arithmetic order so the parity fixtures stay exact.
 */

export type PredictorGender = 'male' | 'female';
export type Percentile = 25 | 50 | 75;
export type Terrain = 'flat' | 'rolling' | 'hilly' | 'mountain';
export type Surface = 'trail' | 'road';
export type PredictionMethod = 'same' | 'band' | 'bandReverse' | 'race' | 'climb' | 'terrain';
export type PredictionWarning = 'softAnchor' | 'staleAnchor' | 'outsideBands' | 'nonStandardDistance';

export interface RacePrediction {
  distance: string;
  km: number;
  seconds: number;
  /** h:mm:ss or m:ss, seconds floored. */
  time: string;
  paceSecondsPerKm: number;
  /** e.g. "5:27/km" (seconds floored, unlike the Pace calculator). */
  pace: string;
  /** The middle half of runners with this known time: 25th and 75th percentile finish. */
  lowSeconds: number;
  highSeconds: number;
  /** 100 minus the median error of this method on held-out real results. */
  confidence: number;
  isUltra: boolean;
  method: PredictionMethod;
  /** Riegel exponent used (road targets) or the race cost applied (ultra targets). */
  factor: number;
  warnings: PredictionWarning[];
}

type RoadKey = '5k' | '10k' | 'hm' | 'mar';
type Band = [lo: number, hi: number, n: number, median: number, p25: number, p75: number, men: number | null, women: number | null];
interface Tables {
  distancesKm: Record<RoadKey, number>;
  roadPairs: Record<string, { n: number; median: number; bands: Band[] }>;
  bridge: { alpha: number; beta: number; residSd: number };
  cost: { c0: number; c1: number; c2: number };
  terrain: Record<Terrain, number>;
  surface: Record<Surface, number>;
  softAnchorSeconds: Record<RoadKey, number>;
  confidence: Record<string, number>;
  races: PredictorRace[];
}
export interface PredictorRace {
  id: string;
  name: string;
  km: number;
  climbPerKm: number;
  cost: number;
  class: Terrain;
  surface: string;
  n: number;
  editions: number;
}
export const PREDICTOR_TABLES = tables as unknown as Tables;
export const PREDICTOR_RACES: PredictorRace[] = PREDICTOR_TABLES.races;

const MARATHON_KM = 42.195;
const ROAD_KEYS: RoadKey[] = ['5k', '10k', 'hm', 'mar'];
/** Standard-normal quantile for the 25th/75th percentile: the middle half. */
const Z_QUARTILE = 0.674;

function paceLabel(pacePerKm: number): string {
  return `${Math.floor(pacePerKm / 60)}:${Math.floor(pacePerKm % 60)
    .toString()
    .padStart(2, '0')}/km`;
}

/** The road distance key for a distance, or null when it is not one of the four. */
export function roadKey(km: number): RoadKey | null {
  for (const key of ROAD_KEYS) {
    if (Math.abs(PREDICTOR_TABLES.distancesKm[key] - km) < 0.1) return key;
  }
  return null;
}

/**
 * Exponent for the pair (from, to) at a known time, interpolated between band
 * midpoints and held at the first/last band outside them. `which` picks the
 * median (sex-specific where the band has 20+ of that sex) or the 25th/75th
 * percentile. Returns null when the pair has no bands.
 */
export function bandExponent(from: RoadKey, to: RoadKey, knownSeconds: number, gender: PredictorGender, which: Percentile): { k: number; outside: boolean } | null {
  const pair = PREDICTOR_TABLES.roadPairs[`${from}>${to}`];
  if (!pair || pair.bands.length === 0) return null;
  const pick = (b: Band): number => {
    if (which === 25) return b[4];
    if (which === 75) return b[5];
    if (gender === 'male' && b[6] !== null) return b[6];
    if (gender === 'female' && b[7] !== null) return b[7];
    return b[3];
  };
  const bands = pair.bands;
  const mids = bands.map((b) => (b[0] + b[1]) / 2);
  if (knownSeconds <= mids[0]) return { k: pick(bands[0]), outside: knownSeconds < bands[0][0] };
  const last = bands.length - 1;
  if (knownSeconds >= mids[last]) return { k: pick(bands[last]), outside: knownSeconds >= bands[last][1] };
  for (let i = 0; i < last; i++) {
    if (knownSeconds >= mids[i] && knownSeconds <= mids[i + 1]) {
      const f = (knownSeconds - mids[i]) / (mids[i + 1] - mids[i]);
      return { k: pick(bands[i]) + (pick(bands[i + 1]) - pick(bands[i])) * f, outside: false };
    }
  }
  return { k: pick(bands[last]), outside: false };
}

/**
 * Time at a road target from a road known race. Longer → shorter iterates,
 * because the bands are keyed on the shorter distance's time.
 */
export function predictRoad(from: RoadKey, knownSeconds: number, to: RoadKey, gender: PredictorGender, which: Percentile): { seconds: number; k: number; method: PredictionMethod; outside: boolean } | null {
  if (from === to) return { seconds: knownSeconds, k: 1, method: 'same', outside: false };
  const dFrom = PREDICTOR_TABLES.distancesKm[from];
  const dTo = PREDICTOR_TABLES.distancesKm[to];
  if (dFrom < dTo) {
    const e = bandExponent(from, to, knownSeconds, gender, which);
    if (!e) return null;
    return { seconds: knownSeconds * Math.pow(dTo / dFrom, e.k), k: e.k, method: 'band', outside: e.outside };
  }
  // Reverse: the pair is (to, from); guess the shorter time, refine three times.
  const pair = PREDICTOR_TABLES.roadPairs[`${to}>${from}`];
  if (!pair) return null;
  const ratio = dFrom / dTo;
  let k = pair.median;
  let shorter = knownSeconds / Math.pow(ratio, k);
  let outside = false;
  for (let i = 0; i < 3; i++) {
    const e = bandExponent(to, from, shorter, gender, which);
    if (!e) return null;
    k = e.k;
    outside = e.outside;
    shorter = knownSeconds / Math.pow(ratio, k);
  }
  return { seconds: shorter, k, method: 'bandReverse', outside };
}

/** The standard road distances that bracket `km` (5K … marathon), clamped at the ends. */
function bracket(km: number): [RoadKey, RoadKey] {
  const d = PREDICTOR_TABLES.distancesKm;
  if (km <= d['5k']) return ['5k', '10k'];
  if (km >= d.mar) return ['hm', 'mar'];
  for (let i = 0; i < ROAD_KEYS.length - 1; i++) {
    if (km >= d[ROAD_KEYS[i]] && km <= d[ROAD_KEYS[i + 1]]) return [ROAD_KEYS[i], ROAD_KEYS[i + 1]];
  }
  return ['hm', 'mar'];
}

/**
 * Time at ANY road distance from a standard known race: predict the two
 * standard distances that bracket the target, then interpolate (or, below 5K
 * and above the marathon, extrapolate) with the local exponent between them.
 */
export function predictRoadAt(from: RoadKey, knownSeconds: number, targetKm: number, gender: PredictorGender, which: Percentile): { seconds: number; k: number; method: PredictionMethod; outside: boolean } | null {
  const toKey = roadKey(targetKm);
  if (toKey) return predictRoad(from, knownSeconds, toKey, gender, which);
  const [a, b] = bracket(targetKm);
  const ta = predictRoad(from, knownSeconds, a, gender, which);
  const tb = predictRoad(from, knownSeconds, b, gender, which);
  if (!ta || !tb) return null;
  const da = PREDICTOR_TABLES.distancesKm[a];
  const db = PREDICTOR_TABLES.distancesKm[b];
  const k = Math.log(tb.seconds / ta.seconds) / Math.log(db / da);
  return { seconds: ta.seconds * Math.pow(targetKm / da, k), k, method: ta.method === 'same' ? tb.method : ta.method, outside: ta.outside || tb.outside };
}

/**
 * A known race at a non-standard road distance is moved to the nearer
 * standard distance with the population median exponent of the pair that
 * brackets it, so the bands can be used. An approximation, flagged as one.
 */
export function standardiseKnown(km: number, seconds: number): { key: RoadKey; seconds: number } {
  const [a, b] = bracket(km);
  const d = PREDICTOR_TABLES.distancesKm;
  const k = PREDICTOR_TABLES.roadPairs[`${a}>${b}`]?.median ?? 1.06;
  const key: RoadKey = Math.abs(Math.log(km / d[a])) <= Math.abs(Math.log(km / d[b])) ? a : b;
  return { key, seconds: seconds * Math.pow(d[key] / km, k) };
}

/** Cost of a race, for a runner of fixed ability, from distance and climb per km, plus the surface offset. */
export function raceCost(km: number, climbPerKm: number, surface: Surface): number {
  const c = PREDICTOR_TABLES.cost;
  return c.c0 + c.c1 * Math.log(km) + c.c2 * climbPerKm + PREDICTOR_TABLES.surface[surface];
}

/** Ultra ability from a marathon time (seconds). */
export function abilityFromMarathon(marathonSeconds: number): number {
  return PREDICTOR_TABLES.bridge.alpha + PREDICTOR_TABLES.bridge.beta * Math.log(marathonSeconds);
}

export function raceById(id: string | undefined | null): PredictorRace | null {
  if (!id) return null;
  return PREDICTOR_RACES.find((r) => r.id === id) ?? null;
}

// ---- Quick mode ----

export interface UltraTarget {
  /** A race from predictorTables.json, whose measured cost is used. */
  raceId?: string;
  /** Otherwise: a terrain class (climb per km preset) or an explicit climb per km, and the surface. */
  terrain?: Terrain;
  climbPerKm?: number;
  surface?: Surface;
}

export interface QuickPredictionInput {
  knownDistanceKm: number;
  knownSeconds: number;
  targetDistanceKm: number;
  gender: PredictorGender;
  /** Where the runner sits among runners with the same known time: 25 (faster quarter), 50 (typical), 75 (slower quarter). */
  percentile: Percentile;
  /** When the known race is itself an ultra: its race or terrain, so its cost can be removed. */
  known?: UltraTarget;
  /** When the target is an ultra: which race or what terrain. Defaults to hilly trail. */
  target?: UltraTarget;
  /** Years since the known race, when known; over two flags a stale anchor. */
  knownAgeYears?: number;
}

/** The old experience levels, mapped onto a position in the measured spread. */
export function percentileFromFatigueFactor(fatigueFactor: number): Percentile {
  if (fatigueFactor <= 1.04) return 25; // Elite
  if (fatigueFactor <= 1.08) return 50; // Experienced, Intermediate: Riegel's 1.06 was the population median
  return 75; // Novice
}

interface CostChoice { cost: number; method: PredictionMethod; confidence: number }

function targetCost(km: number, t: UltraTarget | undefined): CostChoice {
  const race = raceById(t?.raceId);
  if (race) return { cost: race.cost, method: 'race', confidence: PREDICTOR_TABLES.confidence.ultraRace };
  const surface: Surface = t?.surface ?? 'trail';
  if (t?.climbPerKm !== undefined && t.climbPerKm !== null && !Number.isNaN(t.climbPerKm)) {
    return { cost: raceCost(km, t.climbPerKm, surface), method: 'climb', confidence: PREDICTOR_TABLES.confidence.ultraClimb };
  }
  const terrain: Terrain = t?.terrain ?? (surface === 'road' ? 'flat' : 'hilly');
  return { cost: raceCost(km, PREDICTOR_TABLES.terrain[terrain], surface), method: 'terrain', confidence: PREDICTOR_TABLES.confidence.ultraClimb };
}

/** Marathon-equivalent seconds and the road prediction's confidence for a road known race. */
function marathonEquivalent(fromKey: RoadKey, knownSeconds: number, gender: PredictorGender, which: Percentile): { seconds: number; outside: boolean } | null {
  if (fromKey === 'mar') return { seconds: knownSeconds, outside: false };
  const r = predictRoad(fromKey, knownSeconds, 'mar', gender, which);
  return r ? { seconds: r.seconds, outside: r.outside } : null;
}

function shift(which: Percentile): number {
  return which === 25 ? -Z_QUARTILE : which === 75 ? Z_QUARTILE : 0;
}

export function predictQuick(input: QuickPredictionInput): RacePrediction[] | null {
  const distance = input.knownDistanceKm;
  const totalSeconds = input.knownSeconds;
  const target = input.targetDistanceKm;
  if (!distance || !totalSeconds || !target) return null;

  const which = input.percentile;
  const gender = input.gender;
  const warnings: PredictionWarning[] = [];
  // A road known race at a non-standard distance is standardised first; an
  // ultra known race (over the marathon) is handled through its cost below.
  let fromKey = roadKey(distance);
  let knownSeconds = totalSeconds;
  if (!fromKey && distance <= MARATHON_KM) {
    const st = standardiseKnown(distance, totalSeconds);
    fromKey = st.key;
    knownSeconds = st.seconds;
    warnings.push('nonStandardDistance');
  }
  if (fromKey && knownSeconds > PREDICTOR_TABLES.softAnchorSeconds[fromKey]) warnings.push('softAnchor');
  if (input.knownAgeYears !== undefined && input.knownAgeYears > 2) warnings.push('staleAnchor');

  let seconds: number;
  let low: number;
  let high: number;
  let method: PredictionMethod;
  let factor: number;
  let confidence: number;

  if (target <= MARATHON_KM) {
    // Road target. The known race must be a road distance too (an ultra known
    // race goes through the ability, below).
    if (!fromKey) return null;
    const toKey = roadKey(target);
    if (!toKey) warnings.push('nonStandardDistance');
    const chosen = predictRoadAt(fromKey, knownSeconds, target, gender, which);
    if (!chosen) return null;
    const p25 = predictRoadAt(fromKey, knownSeconds, target, gender, 25);
    const p75 = predictRoadAt(fromKey, knownSeconds, target, gender, 75);
    seconds = chosen.seconds;
    low = p25 ? Math.min(p25.seconds, p75 ? p75.seconds : p25.seconds) : seconds;
    high = p75 ? Math.max(p75.seconds, p25 ? p25.seconds : p75.seconds) : seconds;
    method = chosen.method;
    factor = chosen.k;
    if (chosen.outside) warnings.push('outsideBands');
    confidence = chosen.method === 'same' ? 100 : fromKey === 'hm' || toKey === 'hm' ? PREDICTOR_TABLES.confidence.roadFromHalf : fromKey === '10k' || toKey === '10k' ? PREDICTOR_TABLES.confidence.roadFrom10k : PREDICTOR_TABLES.confidence.roadFrom5k;
  } else {
    // Ultra target: ability + cost.
    // ability50 is the typical runner with this known time; ability is the chosen position.
    let ability50: number;
    let ability: number;
    const sd = PREDICTOR_TABLES.bridge.residSd;
    if (fromKey) {
      const m50 = marathonEquivalent(fromKey, knownSeconds, gender, 50);
      const m = which === 50 ? m50 : marathonEquivalent(fromKey, knownSeconds, gender, which);
      if (!m50 || !m) return null;
      if (m.outside) warnings.push('outsideBands');
      ability50 = abilityFromMarathon(m50.seconds);
      // A marathon known race carries no road step to shift, so the percentile moves the ability itself.
      ability = fromKey === 'mar' ? ability50 + shift(which) * sd : abilityFromMarathon(m.seconds);
    } else {
      // The known race is an ultra: remove its cost to get the ability directly.
      const kc = targetCost(distance, input.known);
      ability50 = Math.log(totalSeconds) - kc.cost;
      ability = ability50 + shift(which) * sd;
    }
    const tc = targetCost(target, input.target);
    seconds = Math.exp(ability + tc.cost);
    low = Math.exp(ability50 - Z_QUARTILE * sd + tc.cost);
    high = Math.exp(ability50 + Z_QUARTILE * sd + tc.cost);
    method = tc.method;
    factor = tc.cost;
    confidence = tc.confidence;
  }

  const pacePerKm = seconds / target;
  const targetName = raceById(input.target?.raceId)?.name ?? (standardDistances.find((d) => Math.abs(d.km - target) < 0.1)?.label || `${target}km`);
  return [
    {
      distance: targetName,
      km: target,
      seconds,
      time: formatTimeFromSeconds(seconds),
      paceSecondsPerKm: pacePerKm,
      pace: paceLabel(pacePerKm),
      lowSeconds: low,
      highSeconds: high,
      confidence,
      isUltra: target > MARATHON_KM,
      method,
      factor,
      warnings,
    },
  ];
}

export interface QuickPredictionForm {
  knownDistance: string;
  knownTime: TimeFields;
  targetDistance: string;
  /** "25" | "50" | "75", or one of the old level factors ("1.04" … "1.1") which map onto a percentile. */
  experience: string;
  gender: PredictorGender;
  targetRaceId?: string;
  targetTerrain?: string;
  targetSurface?: string;
  targetClimbPerKm?: string;
}

export function percentileFromForm(experience: string): Percentile {
  const n = parseFloat(experience);
  if (n === 25 || n === 50 || n === 75) return n;
  if (n > 1 && n < 2) return percentileFromFatigueFactor(n);
  return 50;
}

export function quickInputFromForm(form: QuickPredictionForm): QuickPredictionInput {
  const target: UltraTarget = {};
  if (form.targetRaceId) target.raceId = form.targetRaceId;
  if (form.targetTerrain === 'flat' || form.targetTerrain === 'rolling' || form.targetTerrain === 'hilly' || form.targetTerrain === 'mountain') target.terrain = form.targetTerrain;
  if (form.targetSurface === 'road' || form.targetSurface === 'trail') target.surface = form.targetSurface;
  if (form.targetClimbPerKm && !Number.isNaN(parseFloat(form.targetClimbPerKm))) target.climbPerKm = parseFloat(form.targetClimbPerKm);
  return {
    knownDistanceKm: parseFloat(form.knownDistance),
    knownSeconds: secondsFromFields(form.knownTime),
    targetDistanceKm: parseFloat(form.targetDistance),
    gender: form.gender,
    percentile: percentileFromForm(form.experience),
    target: Object.keys(target).length ? target : undefined,
  };
}

// ---- Advanced mode: two known races ----

export interface AdvancedPredictionInput {
  race1DistanceKm: number;
  race1Seconds: number;
  race2DistanceKm: number;
  race2Seconds: number;
  gender: PredictorGender;
  percentile: Percentile;
  target?: UltraTarget;
}

export const ADVANCED_DISTANCES = [
  { name: '5K', km: 5, isUltra: false },
  { name: '10K', km: 10, isUltra: false },
  { name: 'Half Marathon', km: 21.0975, isUltra: false },
  { name: 'Marathon', km: 42.195, isUltra: false },
  { name: '50K', km: 50, isUltra: true },
  { name: '50 Miles', km: 80.4672, isUltra: true },
  { name: '100K', km: 100, isUltra: true },
  { name: '100 Miles', km: 160.934, isUltra: true },
];

/** True when both races are filled in. */
export function advancedInputIsComplete(i: AdvancedPredictionInput): boolean {
  return !(!i.race1DistanceKm || !i.race1Seconds || !i.race2DistanceKm || !i.race2Seconds);
}

/** Race #1 must be shorter than Race #2; the form shows an alert otherwise. */
export function advancedRaceOrderIsValid(i: AdvancedPredictionInput): boolean {
  return i.race1DistanceKm < i.race2DistanceKm;
}

export interface AdvancedPrediction extends RacePrediction {
  /** Which known race the prediction came from (the nearer in log-distance). */
  anchor: 1 | 2;
  /** The same target predicted from the other race, as a cross-check. */
  crossCheckSeconds: number | null;
}

/**
 * Two races are two anchors: each target is predicted from the race nearer to
 * it in log-distance, and the other race's prediction is reported beside it.
 * A personal exponent from two races was tested on 40,939 athletes and
 * predicts worse than Riegel's 1.06 (8.9% against 7.3%; the bands give 4.0%),
 * so it is not used, and neither are age, weight or height, which add nothing
 * once the time is known. Null when inputs are incomplete or out of order.
 */
export function predictAdvanced(input: AdvancedPredictionInput): AdvancedPrediction[] | null {
  if (!advancedInputIsComplete(input) || !advancedRaceOrderIsValid(input)) return null;
  const from = (distanceKm: number, seconds: number, target: number): RacePrediction | null =>
    predictQuick({ knownDistanceKm: distanceKm, knownSeconds: seconds, targetDistanceKm: target, gender: input.gender, percentile: input.percentile, target: input.target })?.[0] ?? null;
  const out: AdvancedPrediction[] = [];
  for (const d of ADVANCED_DISTANCES) {
    const d1 = Math.abs(Math.log(d.km / input.race1DistanceKm));
    const d2 = Math.abs(Math.log(d.km / input.race2DistanceKm));
    const anchor: 1 | 2 = d1 <= d2 ? 1 : 2;
    const primary = anchor === 1 ? from(input.race1DistanceKm, input.race1Seconds, d.km) : from(input.race2DistanceKm, input.race2Seconds, d.km);
    const other = anchor === 1 ? from(input.race2DistanceKm, input.race2Seconds, d.km) : from(input.race1DistanceKm, input.race1Seconds, d.km);
    if (!primary) continue;
    out.push({ ...primary, distance: d.name, anchor, crossCheckSeconds: other ? other.seconds : null });
  }
  return out.length ? out : null;
}

export interface AdvancedPredictionForm {
  race1Distance: string;
  race1Time: TimeFields;
  race2Distance: string;
  race2Time: TimeFields;
  gender: PredictorGender;
  experience?: string;
  targetTerrain?: string;
  targetSurface?: string;
}

export function advancedInputFromForm(form: AdvancedPredictionForm): AdvancedPredictionInput {
  const target: UltraTarget = {};
  if (form.targetTerrain === 'flat' || form.targetTerrain === 'rolling' || form.targetTerrain === 'hilly' || form.targetTerrain === 'mountain') target.terrain = form.targetTerrain;
  if (form.targetSurface === 'road' || form.targetSurface === 'trail') target.surface = form.targetSurface;
  return {
    race1DistanceKm: parseFloat(form.race1Distance),
    race1Seconds: secondsFromFields(form.race1Time),
    race2DistanceKm: parseFloat(form.race2Distance),
    race2Seconds: secondsFromFields(form.race2Time),
    gender: form.gender,
    percentile: percentileFromForm(form.experience ?? '50'),
    target: Object.keys(target).length ? target : undefined,
  };
}
