/**
 * Word Run's answers, in the order they are played (Stephen, 2 Oct 2026). Each length has its
 * own queue: the schedule takes the next word of the day's length. Add new words at the END of a
 * list, never in the middle, or every later puzzle changes. Facts are tips, definitions and
 * well-documented history only: a wrong fact undoes the point of the reveal. No em dashes.
 */
export interface Answer {
  word: string;
  fact: string;
  /** A page on filmmyrun.com that follows on from the fact. */
  link?: { label: string; href: string };
}

const CALC = { label: 'Pace calculators', href: '/tools/calculators' };
const SHOES = { label: 'Shoe Finder', href: '/tools/shoe-finder' };
const PARKRUN = { label: 'parkrun stats', href: '/tools/parkrun' };
const NEWS = { label: 'Running news', href: '/news' };

export const ANSWERS: Record<4 | 5 | 6 | 7, Answer[]> = {
  4: [
    { word: 'PACE', fact: 'Pace is time per mile or kilometre, the reverse of speed. Most runners start too fast and pay for it later.', link: CALC },
    { word: 'FELL', fact: 'From the Old Norse fjall, a mountain. Fell running grew up in the Lake District and the Pennines, often with no marked route.' },
    { word: 'GELS', fact: 'A typical energy gel carries 20 to 25 g of carbohydrate. Take it with water, not on its own.' },
    { word: 'MILE', fact: 'Roger Bannister ran the first sub-four-minute mile, 3:59.4, at Iffley Road in Oxford on 6 May 1954.' },
    { word: 'BONK', fact: 'Bonking is running out of stored glycogen. Legs empty, mood drops, and the only cure is sugar.' },
    { word: 'TRIG', fact: 'Ordnance Survey began building its concrete trig pillars in 1936 to remap Great Britain. Touching one is the law on a fell summit.' },
    { word: 'HILL', fact: 'Hill reps build strength with less pounding than speedwork on the flat. Run up hard, jog down easy.' },
    { word: 'LAPS', fact: 'One lap of a standard outdoor track, in lane one, is 400 m. Twenty-five of them make a 10,000 m race.' },
    { word: 'DROP', fact: "A shoe's drop is the difference in height between heel and forefoot, in millimetres. Change it gradually, your calves will thank you.", link: SHOES },
    { word: 'WALL', fact: 'In the marathon, the wall usually arrives around 20 miles, when glycogen runs low. Fuelling early pushes it back.' },
    { word: 'BECK', fact: 'Beck is the Lake District word for a stream, from Old Norse. Expect to cross several on any fell race.' },
    { word: 'KICK', fact: "A kick is the final burst for the line. A long run of even pace usually leaves more in the legs for it." },
    { word: 'GAIT', fact: 'Your gait is the way you run. A gait analysis films you on a treadmill to see how your foot lands and rolls.' },
    { word: 'HALF', fact: 'A half marathon is 21.0975 km, or 13.1 miles. Many runners find it the most satisfying distance to race.' },
    { word: 'CALF', fact: 'Calf strains are common when runners switch to lower-drop shoes or start running on their toes. Build up slowly.' },
    { word: 'TARN', fact: 'A tarn is a small mountain lake, usually in a hollow carved out by a glacier. The Lakes have dozens.' },
    { word: 'LACE', fact: 'A heel lock, using the extra top eyelet most shoes have, stops your heel lifting on long descents.', link: SHOES },
    { word: 'VEST', fact: 'Club vests are worn with pride and often decades out of date. Race in your club colours and someone will shout your club name.' },
    { word: 'SALT', fact: 'Sweat carries sodium out with it. On long, hot runs, electrolytes matter as much as water.' },
    { word: 'PIKE', fact: 'Scafell Pike is the highest mountain in England at 978 m. Pike is a common Lakeland word for a peaked summit.' },
    { word: 'SHIN', fact: 'Shin splints are often a sign of doing too much, too soon. Rest, then build back with smaller jumps in mileage.' },
    { word: 'LOOP', fact: 'A loop course means one long way round with no backtracking. Lap races, by contrast, pass the same aid station again and again.' },
    { word: 'BIBS', fact: 'Race bibs carry a timing chip on the back in most big races. Pin it on the front, folding it can break the chip.' },
    { word: 'HEAT', fact: 'In the heat, slow down early rather than late. Every degree above about 15°C costs time in a marathon.' },
    { word: 'MOOR', fact: 'Moorland running means peat, heather and bog. Footing is everything, so shorten your stride.' },
    { word: 'TAPE', fact: 'Breaking the finish tape is reserved for the winner. Kinesiology tape, the stretchy kind, is for everyone else.' },
    { word: 'KNEE', fact: "Runner's knee, a pain around the kneecap, often comes from weak hips. Strength work helps more than rest alone." },
    { word: 'GILL', fact: 'A gill, sometimes spelt ghyll, is a narrow ravine with a stream. Wordsworth helped make the ghyll spelling popular.' },
    { word: 'FUEL', fact: 'For events over two hours, aim for 60 to 90 g of carbohydrate an hour. Practise it in training, not on race day.' },
    { word: 'CLUB', fact: 'Running clubs in the UK go back to the 1860s. Most still welcome beginners, and the post-run cake is usually free.' },
    { word: 'PEAK', fact: 'Plans build to a peak week two or three weeks before the race, then taper. Fitness peaks after the training, not during.' },
    { word: 'SOCK', fact: 'Cotton socks hold water and cause blisters. Synthetic or merino wool socks wick sweat away.' },
    { word: 'TROT', fact: 'The Thanksgiving Turkey Trot is the most popular day of the year for races in America. Britain has its Christmas Day parkruns.', link: PARKRUN },
    { word: 'WIND', fact: "Running into a headwind costs more than a tailwind gives back. Tuck in behind another runner when you can." },
    { word: 'DALE', fact: 'Dale is an old word for valley. The Yorkshire Dales are home to the Three Peaks Race, first run in 1954.' },
    { word: 'EASY', fact: 'Most of your running should feel easy: able to talk in full sentences. Easy days make hard days possible.' },
    { word: 'CRAG', fact: 'A crag is a steep, rocky outcrop. On a fell race, the line round it is often faster than the line over it.' },
    { word: 'STEP', fact: 'Most runners take between 150 and 190 steps a minute. Shorter, quicker steps reduce the load on each landing.' },
    { word: 'TEAM', fact: 'Cross country is scored by team: add up your counters\' places and the lowest total wins. Every place matters.' },
    { word: 'HEEL', fact: 'Heel striking is not wrong in itself. What matters more is landing with your foot close under your body.' },
    { word: 'BEEP', fact: 'The bleep test, or multi-stage fitness test, was published in 1982. Every PE class in Britain has feared it since.' },
    { word: 'GATE', fact: 'On fell and trail races, leave every gate as you found it. A marshal may be watching, so will a farmer.' },
    { word: 'FOAM', fact: 'Light, springy foam in the Nike Vaporfly changed road racing from 2017. A foam roller is the cheaper foam in your house.', link: SHOES },
    { word: 'LANE', fact: 'In a 200 m or 400 m race, runners stay in their lanes, with staggered starts so everyone runs the same distance.' },
    { word: 'GRIT', fact: 'Gritstone edges of the Peak District give some of the best trail running in England, and the grippiest rock.' },
    { word: 'ACHE', fact: 'Muscle soreness that peaks a day or two after a hard run is normal. Sharp pain that gets worse as you run is not.' },
    { word: 'PACK', fact: 'Running in a pack saves energy, and the pack usually splits on the last climb. Know where that climb is.' },
    { word: 'FORD', fact: 'Rivers on fell races can rise fast after rain. Organisers can and do change the route when a ford is unsafe.' },
    { word: 'BASE', fact: 'Base training is weeks of easy, steady mileage before any speedwork. It builds the engine the hard sessions rely on.' },
    { word: 'LEGS', fact: "Legs gone? Shorten your stride and keep your arms moving. Arms set the rhythm the legs follow." },
    { word: 'SNOW', fact: 'In snow, shoes with deep lugs or microspikes help. Run on the fresh snow beside trodden paths, it grips better.' },
    { word: 'ROAD', fact: 'Road races in the UK are measured by the shortest possible line, so your watch will almost always say a little more.' },
    { word: 'PLOD', fact: 'A slow plod still counts. Time on your feet builds endurance whatever the pace.' },
    { word: 'TIME', fact: 'Gun time starts when the race starts. Chip time starts when you cross the line. Records use gun time.' },
    { word: 'PATH', fact: 'A public right of way in England may be a footpath, bridleway or byway. Runners can use them all.' },
    { word: 'JOGS', fact: 'Jogging became a craze after Bill Bowerman co-wrote the book Jogging in 1966. He also co-founded Nike.' },
  ],
  5: [
    { word: 'TRAIL', fact: "Trail shoes have deeper lugs and a tougher upper than road shoes. On hard-packed trails, road shoes are often fine.", link: SHOES },
    { word: 'TAPER', fact: 'Most marathon plans taper for two to three weeks. You lose almost no fitness, and you arrive with fresh legs.' },
    { word: 'CAIRN', fact: 'A cairn is a pile of stones marking a summit or path, from the Gaelic carn. Add a stone if you like, never take one.' },
    { word: 'CHAFE', fact: 'Chafing is friction on skin made worse by sweat. Petroleum jelly or anti-chafe balm before a long run saves misery.' },
    { word: 'RELAY', fact: 'In relays, the baton must pass inside the changeover zone. Drop it and the race usually goes with it.' },
    { word: 'TEMPO', fact: 'A tempo run is comfortably hard: you could speak a few words, not a sentence. Usually 20 to 40 minutes.' },
    { word: 'SCREE', fact: 'Scree is loose rock on a slope. Descending it well is a fell running skill: keep your weight forward and move your feet fast.' },
    { word: 'PACER', fact: 'Pacers in big marathons carry flags or balloons with a finish time. Stick with them early, decide later.' },
    { word: 'ULTRA', fact: 'An ultramarathon is any distance beyond the marathon\'s 42.195 km. The most common distances are 50 km, 50 miles, 100 km and 100 miles.' },
    { word: 'SPLIT', fact: 'A negative split means running the second half faster than the first. Most world records are run this way or close to it.', link: CALC },
    { word: 'STILE', fact: 'A stile lets walkers over a wall or fence. In a race, the queue at the first stile can cost more time than the hills.' },
    { word: 'CRAMP', fact: 'The cause of exercise cramp is still argued over. Fatigue seems to matter more than salt, so pace well.' },
    { word: 'RIDGE', fact: 'Ridge running is as exposed as it is beautiful. In cloud or high winds, the lower path is often the better choice.' },
    { word: 'MEDAL', fact: 'Some runners keep every medal. Others give them away. Either way, they are the only things you can\'t buy at the expo.' },
    { word: 'TOKYO', fact: 'Tokyo joined the World Marathon Majors in 2013. Its course finishes near Tokyo Station.' },
    { word: 'SWEAT', fact: 'Runners can lose anything from half a litre to two litres of sweat an hour. Weighing yourself before and after a run tells you yours.' },
    { word: 'CLIMB', fact: 'On steep climbs, power hiking with hands on thighs is often as fast as running, and much cheaper.' },
    { word: 'TRACK', fact: 'Track sessions are great for pace judgement: every 100 m is marked, so you can\'t kid yourself.' },
    { word: 'BOTHY', fact: 'A bothy is a simple mountain shelter, free to use. The Mountain Bothies Association looks after about 100 in Britain.' },
    { word: 'QUADS', fact: 'Long descents wreck the quads because the muscle works while lengthening. Train downhill before a hilly race.' },
    { word: 'SPIKE', fact: 'Track spikes screw in from below. Cross country spikes are longer, often 12 to 15 mm on deep mud.' },
    { word: 'START', fact: 'The start line is the most dangerous place in a race for your plan. Everyone feels fresh and everyone goes too fast.' },
    { word: 'TORCH', fact: 'Night sections of ultras need a head torch and spare batteries. Most races list both as compulsory kit.' },
    { word: 'LUNGS', fact: "Breathless on easy runs? Slow down. Easy should feel easy for your lungs and your legs." },
    { word: 'ROUND', fact: 'The Bob Graham Round links 42 Lakeland peaks in under 24 hours. Bob Graham set it in 1932.' },
    { word: 'WATER', fact: 'Drinking to thirst is enough for most races. Drinking far more than you sweat can be dangerous.' },
    { word: 'SURGE', fact: 'A surge is a sudden change of pace to break the group. Responding costs energy too, so choose which ones to cover.' },
    { word: 'CROSS', fact: 'The English National Cross Country Championships date back to the 1870s. Mud has been involved since the start.' },
    { word: 'HEART', fact: 'Resting heart rate falls as you get fitter. A sudden rise in the morning can be an early sign of illness or tiredness.' },
    { word: 'POLES', fact: 'Poles help on long climbs in mountain ultras. Some races ban them, so check the rules before you pack.' },
    { word: 'ANKLE', fact: 'Single-leg balance work strengthens ankles for rough ground. Stand on one leg while you brush your teeth.' },
    { word: 'QUEUE', fact: 'The toilet queue at a big marathon start can take longer than the first mile. Get there early.' },
    { word: 'LACES', fact: 'Double knot your laces before a race. Stopping to retie them costs far more than the extra few seconds.' },
    { word: 'MUDDY', fact: 'On a muddy course, short steps and a high cadence keep you upright. Long strides end in the mud.' },
    { word: 'STEEP', fact: 'On very steep ground, short steps uphill and quick feet downhill beat any heroic effort.' },
    { word: 'CARBS', fact: 'Carbohydrate loading works best over two or three days before a long race, not in one big pasta meal the night before.' },
    { word: 'FLASK', fact: 'Soft flasks shrink as you drink, so they don\'t slosh. Most trail vests carry two at the front.' },
    { word: 'LAYER', fact: 'Dress for the second mile, not the first. If you\'re warm at the start, you\'re overdressed.' },
    { word: 'SPEED', fact: 'Speedwork is a small part of most good training plans, often 10 to 20 percent. The rest is easy running.' },
    { word: 'RIVER', fact: 'The Thames Path follows the river for 184 miles from its source in the Cotswolds to the Thames Barrier.' },
    { word: 'ELITE', fact: 'Elite athletes start at the front of big marathons and have their own drinks tables, with their bottles marked.' },
    { word: 'DRINK', fact: 'At a drinks station, pinch the top of the paper cup into a spout. You\'ll drink more and wear less.' },
    { word: 'SOCKS', fact: 'Toe socks stop toes rubbing against each other. Runners either swear by them or have never tried them.' },
    { word: 'GLUTE', fact: 'Strong glutes keep your hips level as you land. Weak ones are behind many knee and hip niggles.' },
    { word: 'STONE', fact: 'UTMB Running Stones are earned at UTMB World Series races and give entry to the Mont-Blanc lottery.', link: { label: 'StoneTracker', href: '/tools/stone-tracker' } },
    { word: 'DIARY', fact: 'A training diary shows you what worked. Note how you felt as well as how far you ran.' },
    { word: 'HILLY', fact: 'On a hilly course, run to effort, not pace. Your watch will lie to you on the climbs and the descents.' },
    { word: 'SLEEP', fact: 'Sleep is when training turns into fitness. The night before the night before a race matters most.' },
    { word: 'WATCH', fact: 'GPS watches lose accuracy among tall buildings and under trees. Trust the mile markers over your wrist.' },
    { word: 'JELLY', fact: 'Jelly babies have fuelled British runners for decades. The aid station bowl is a national institution.' },
    { word: 'MARSH', fact: 'Crossing boggy ground, step on tufts of grass and heather. Bright green moss usually means deep water.' },
    { word: 'PASTA', fact: 'Pasta parties the night before a marathon are a tradition. Eat what you know, not a giant plate of something new.' },
    { word: 'GLOVE', fact: 'Cold hands slow you more than you think. Thin gloves weigh almost nothing and fit in any pocket.' },
    { word: 'BOGGY', fact: 'Bog trotters say the shortest line across a moor is rarely the driest. Local knowledge is worth minutes.' },
    { word: 'LYCRA', fact: 'Lycra, or elastane, was invented by DuPont in 1958. Running fashion has never fully recovered.' },
    { word: 'STRAP', fact: 'Chest strap heart rate monitors are more accurate than wrist sensors, especially in intervals.' },
  ],
  6: [
    { word: 'STRIDE', fact: 'Strides are short, relaxed accelerations of about 20 seconds. A few after an easy run sharpen your form.' },
    { word: 'BOSTON', fact: 'The Boston Marathon was first run in 1897, the year after the first Olympic marathon. It is the oldest annual marathon in the world.', link: NEWS },
    { word: 'NIGGLE', fact: 'A niggle is the small ache before an injury. Two easy days now can save two months later.' },
    { word: 'CAMBER', fact: 'Roads slope away from the middle to drain water. Running the same side every day loads one leg more.' },
    { word: 'BUCKLE', fact: 'Western States finishers get a belt buckle: silver for under 24 hours, bronze for everyone else inside the 30-hour cut-off.' },
    { word: 'SPRINT', fact: 'The fastest humans reach their top speed around 60 m into a 100 m race. Nobody accelerates all the way.' },
    { word: 'GAITER', fact: 'Trail gaiters keep stones and grit out of your shoes. On a dusty course they save your feet.' },
    { word: 'TARTAN', fact: 'Tartan was the trade name of the first all-weather synthetic tracks. The 1968 Mexico City Olympics were the first to use one.' },
    { word: 'SUMMIT', fact: 'In mountain races, the summit is rarely the halfway point in time. The descent is where races are won and lost.' },
    { word: 'BALLOT', fact: 'Hundreds of thousands of people enter the London Marathon ballot every year. Most are unlucky, and try again next year.', link: NEWS },
    { word: 'TENDON', fact: 'The Achilles is the strongest tendon in the body. Heavy, slow calf raises are the standard rehab for it.' },
    { word: 'CINDER', fact: 'Before synthetic tracks, races were run on cinders. Bannister\'s four-minute mile was run on a cinder track.' },
    { word: 'PODIUM', fact: 'Age-group podiums make many runners\' seasons. Turn up to the prize giving, they do call the names.' },
    { word: 'SPARTA', fact: 'The Spartathlon runs 246 km from Athens to Sparta, ending when runners touch the foot of the statue of King Leonidas.', link: NEWS },
    { word: 'THIRST', fact: 'For most runners in most races, thirst is a good guide to how much to drink.' },
    { word: 'MIDGES', fact: 'Scottish midges are worst from late May to September, on still, damp evenings. Keep moving.' },
    { word: 'SPLITS', fact: 'Even splits are usually the fastest way to run any distance from 5 km up.', link: CALC },
    { word: 'CUTOFF', fact: 'Ultras set cut-off times at checkpoints. Missing one usually ends your race, so know them before you start.' },
    { word: 'BERLIN', fact: 'Berlin\'s flat, fast course has seen more men\'s marathon world records than any other.', link: NEWS },
    { word: 'INSOLE', fact: 'The insole that comes with your shoe can be swapped. Take your orthotics shoe shopping.', link: SHOES },
    { word: 'PUDDLE', fact: 'In a trail race, going round a puddle widens the path and wrecks the verge. Go straight through.' },
    { word: 'ASCENT', fact: 'Naismith\'s rule, written for walkers in 1892, adds an hour for every 600 m of climbing. Runners pay a similar price.' },
    { word: 'TIMING', fact: 'Most race timing chips use radio frequency. Mats at the start and finish read them as you cross.' },
    { word: 'PHYSIO', fact: 'See a physio about pain that changes how you run. Limping on is how a niggle turns into a stress fracture.' },
    { word: 'LONDON', fact: 'The first London Marathon was run in 1981. It calls itself the largest annual one-day fundraising event in the world.', link: NEWS },
    { word: 'VALLEY', fact: 'Valley bottoms are colder than slopes on clear nights, as cold air sinks. Pack a layer for the low checkpoints.' },
    { word: 'BEANIE', fact: 'A thin hat on a cold day lets you dress lighter elsewhere. Take it off when you warm up.' },
    { word: 'OXYGEN', fact: 'VO2 max is the most oxygen your body can use. It can rise with training, but it isn\'t the only thing that decides your race.' },
    { word: 'JACKET', fact: 'Fell races often require a waterproof jacket with taped seams. A windproof doesn\'t count.' },
    { word: 'UPHILL', fact: 'Uphill running is speedwork in disguise. Your heart rate rises without the pounding of fast running on the flat.' },
    { word: 'TROPHY', fact: 'Many club trophies are older than the members racing for them. Check the names engraved on the base.' },
    { word: 'NETTLE', fact: 'Nettles sting through thin tights. Trail runners in shorts learn the dock leaf cure early.' },
    { word: 'PACING', fact: 'Pacing is the most underrated skill in running. It costs nothing and is worth minutes.', link: CALC },
    { word: 'SODIUM', fact: 'Sweat is salty because it carries sodium. Salty sweaters see white marks on their kit after a long run.' },
    { word: 'BRIDGE', fact: 'Glute bridges are among the simplest strength exercises for runners. No gym needed.' },
    { word: 'RUNNER', fact: 'All you need to be a runner is a pair of shoes and a door. That\'s why so many of us are.' },
    { word: 'FOREST', fact: 'Forest trails are kinder to the legs than tarmac. Roots and leaves hide trip hazards, so lift your feet.' },
    { word: 'TOILET', fact: 'Every runner has a toilet story. Trail etiquette: well away from water and paths, and take your paper with you.' },
    { word: 'SHORTS', fact: 'Split shorts give the most freedom of movement. Pockets for gels are the modern upgrade.' },
    { word: 'COFFEE', fact: 'Caffeine is one of the few legal aids with good evidence for endurance. Try it in training before race day.' },
    { word: 'STEADY', fact: 'A steady run sits between easy and tempo. Many runners run all their miles here by accident.' },
    { word: 'BANANA', fact: 'A banana carries about 25 g of carbohydrate. Nature\'s energy gel, in its own wrapper.' },
    { word: 'TIGHTS', fact: 'Compression tights claim to reduce muscle vibration. The evidence is mixed, but they keep your legs warm.' },
    { word: 'INJURY', fact: 'Most running injuries come from doing too much, too soon. Increase weekly mileage gradually.' },
    { word: 'STREAM', fact: 'In the hills, streams look clean but may not be. Filter bottles are cheap and light.' },
    { word: 'ROLLER', fact: 'Foam rolling feels good and may help you move better. It won\'t fix a real injury.' },
    { word: 'NUMBER', fact: 'Writing your name on your race number gets you cheered by strangers all the way round.' },
    { word: 'RACING', fact: 'Racing teaches what training can\'t. A few low-key races before your goal race are worth the entry fee.' },
    { word: 'JUNIOR', fact: 'Junior parkrun is 2 km, for children aged 4 to 14, on Sunday mornings.', link: PARKRUN },
    { word: 'MEDALS', fact: 'At the Olympics, gold medals are mostly silver, with a thin plating of gold.' },
    { word: 'GRAVEL', fact: 'Gravel paths are fast and forgiving. Loose gravel on a descent is not, so shorten your stride.' },
    { word: 'AUTUMN', fact: 'Autumn is marathon season: Berlin, Chicago and New York all fall between late September and early November.', link: NEWS },
    { word: 'SPONGE', fact: 'Some big races hand out sponges on hot days. Squeeze the water over your head, not into your shoes.' },
    { word: 'TARMAC', fact: 'Tarmac is harder than trail but more even underfoot. Your legs adapt to whatever surface you train on most.' },
    { word: 'WINTER', fact: 'Winter training builds spring PBs. Dark mornings need a light and something reflective.' },
    { word: 'ENERGY', fact: 'The energy drink at aid stations is often a different brand from the one you trained with. Check before race day.' },
  ],
  7: [
    { word: 'FARTLEK', fact: 'Fartlek is Swedish for speed play. Gösta Holmér developed it in the 1930s: fast and slow running by feel, not by the watch.' },
    { word: 'PARKRUN', fact: 'parkrun began on 2 October 2004 at Bushy Park in south-west London, with 13 runners. Its name is always lower case.', link: PARKRUN },
    { word: 'BLISTER', fact: 'Blisters come from friction, heat and moisture. Treat a hot spot before it becomes a blister.' },
    { word: 'CADENCE', fact: 'The 180 steps a minute target comes from Jack Daniels counting elite runners\' steps at the 1984 Olympics. Your best cadence may differ.' },
    { word: 'CHICAGO', fact: 'Kelvin Kiptum set the men\'s marathon world record of 2:00:35 in Chicago in 2023. Ruth Chepngetich set the women\'s, 2:09:56, there in 2024.', link: NEWS },
    { word: 'HARRIER', fact: 'Many British clubs are called Harriers, after the hare and hounds paper chases that began club cross country in the 1800s.' },
    { word: 'TOWPATH', fact: 'Canal towpaths were built for horses pulling boats. They make flat, traffic-free running routes through towns and cities.' },
    { word: 'LACTATE', fact: 'Lactate doesn\'t cause next-day soreness. Your body uses it as fuel, and it clears within an hour of a hard session.' },
    { word: 'MARSHAL', fact: 'Marshals stand in the cold so you can race. Thank every one of them.' },
    { word: 'DESCENT', fact: 'Good descenders look ahead, not at their feet, and let gravity do the work. It takes practice.' },
    { word: 'TOENAIL', fact: 'Black toenails come from toes hitting the front of the shoe, often on descents. A half size up can help.', link: SHOES },
    { word: 'LOTTERY', fact: 'Western States, UTMB and Hardrock all use lotteries, as many more people want to race than there are places.' },
    { word: 'STRETCH', fact: 'Static stretching before a run doesn\'t prevent injury. Save it for afterwards, and warm up by jogging.' },
    { word: 'COMPASS', fact: 'Fell races often require a map and compass as compulsory kit. Carrying one helps only if you can use it.' },
    { word: 'MIDSOLE', fact: 'The midsole is the foam between your foot and the road. It is where almost all the recent shoe innovation lives.', link: SHOES },
    { word: 'HAIRPIN', fact: 'On a zigzag path, cutting the corners erodes the hillside. Stick to the line, it is usually quicker anyway.' },
    { word: 'PROTEIN', fact: 'Protein after a hard run helps your muscles repair. A glass of milk does the job well.' },
    { word: 'BRAMBLE', fact: 'Bramble scratches are a sign of a proper trail run. Long socks are the trail runner\'s armour.' },
    { word: 'TRAINER', fact: 'In Britain we call running shoes trainers. In America, a trainer is a person who looks after athletes.' },
    { word: 'PLATEAU', fact: 'A training plateau often means you need more rest, not more training. Fitness is built during recovery.' },
    { word: 'HYDRATE', fact: 'You can\'t hydrate in advance by drinking far more than normal. Your kidneys just pass it straight on.' },
    { word: 'BEARING', fact: 'Taking a bearing means lining up the compass with the map, then following the arrow. Practise in clear weather first.' },
    { word: 'CUSHION', fact: 'More cushioning doesn\'t always mean fewer injuries. The best shoe is often simply the most comfortable one.', link: SHOES },
    { word: 'RECOVER', fact: 'A rough rule of thumb is one easy day for every mile raced. A marathon deserves a few weeks of gentle running.' },
    { word: 'POSTURE', fact: 'Run tall, with relaxed shoulders. When you tire, check your shoulders first, they creep up.' },
    { word: 'BREATHE', fact: 'Breathing through your mouth is fine when running hard. You need all the air you can get.' },
    { word: 'MASSAGE', fact: 'Sports massage helps many runners feel looser. Book it a few days before a race, not the day before.' },
    { word: 'SUNBURN', fact: 'Long runs mean hours in the sun. Sun cream on the back of the neck and the tops of the ears is easily forgotten.' },
  ],
};
