/**
 * Fartlex's answers (the code keeps its first name, word-run), in the order they are played (Stephen, 2 Oct 2026). Each length has its
 * own queue: the schedule takes the next word of the day's length. Add new words at the END of a
 * list, never in the middle, or every later puzzle changes. Facts are tips, definitions and
 * well-documented history only: a wrong fact undoes the point of the reveal. No em dashes.
 */
export interface Answer {
  word: string;
  fact: string;
  /** A page on filmmyrun.com that follows on from the fact. */
  link?: { label: string; href: string };
}

const CALC = { label: 'Pace calculators', href: '/tools/calculators' };
const SHOES = { label: 'Shoe Finder', href: '/tools/shoe-finder' };
const PARKRUN = { label: 'parkrun stats', href: '/tools/parkrun' };
const NEWS = { label: 'Running news', href: '/news' };

export const ANSWERS: Record<4 | 5 | 6 | 7, Answer[]> = {
  4: [
    { word: 'PACE', fact: 'Pace is time per mile or kilometre, the reverse of speed. Most runners start too fast and pay for it later.', link: CALC },
    { word: 'FELL', fact: 'From the Old Norse fjall, a mountain. Fell running grew up in the Lake District and the Pennines, often with no marked route.' },
    { word: 'GELS', fact: 'A typical energy gel carries 20 to 25 g of carbohydrate. Take it with water, not on its own.' },
    { word: 'MILE', fact: 'Roger Bannister ran the first sub-four-minute mile, 3:59.4, at Iffley Road in Oxford on 6 May 1954.' },
    { word: 'BONK', fact: 'Bonking is running out of stored glycogen. Legs empty, mood drops, and the only cure is sugar.' },
    { word: 'TRIG', fact: 'Ordnance Survey began building its concrete trig pillars in 1936 to remap Great Britain. Touching one is the law on a fell summit.' },
    { word: 'HILL', fact: 'Hill reps build strength with less pounding than speedwork on the flat. Run up hard, jog down easy.' },
    { word: 'LAPS', fact: 'One lap of a standard outdoor track, in lane one, is 400 m. Twenty-five of them make a 10,000 m race.' },
    { word: 'DROP', fact: "A shoe's drop is the difference in height between heel and forefoot, in millimetres. Change it gradually, your calves will thank you.", link: SHOES },
    { word: 'WALL', fact: 'In the marathon, the wall usually arrives around 20 miles, when glycogen runs low. Fuelling early pushes it back.' },
    { word: 'BECK', fact: 'Beck is the Lake District word for a stream, from Old Norse. Expect to cross several on any fell race.' },
    { word: 'KICK', fact: "A kick is the final burst for the line. A long run of even pace usually leaves more in the legs for it." },
    { word: 'GAIT', fact: 'Your gait is the way you run. A gait analysis films you on a treadmill to see how your foot lands and rolls.' },
    { word: 'HALF', fact: 'A half marathon is 21.0975 km, or 13.1 miles. Many runners find it the most satisfying distance to race.' },
    { word: 'CALF', fact: 'Calf strains are common when runners switch to lower-drop shoes or start running on their toes. Build up slowly.' },
    { word: 'TARN', fact: 'A tarn is a small mountain lake, usually in a hollow carved out by a glacier. The Lakes have dozens.' },
    { word: 'LACE', fact: 'A heel lock, using the extra top eyelet most shoes have, stops your heel lifting on long descents.', link: SHOES },
    { word: 'VEST', fact: 'Club vests are worn with pride and often decades out of date. Race in your club colours and someone will shout your club name.' },
    { word: 'SALT', fact: 'Sweat carries sodium out with it. On long, hot runs, electrolytes matter as much as water.' },
    { word: 'PIKE', fact: 'Scafell Pike is the highest mountain in England at 978 m. Pike is a common Lakeland word for a peaked summit.' },
    { word: 'SHIN', fact: 'Shin splints are often a sign of doing too much, too soon. Rest, then build back with smaller jumps in mileage.' },
    { word: 'LOOP', fact: 'A loop course means one long way round with no backtracking. Lap races, by contrast, pass the same aid station again and again.' },
    { word: 'BIBS', fact: 'Race bibs carry a timing chip on the back in most big races. Pin it on the front, folding it can break the chip.' },
    { word: 'HEAT', fact: 'In the heat, slow down early rather than late. Every degree above about 15°C costs time in a marathon.' },
    { word: 'MOOR', fact: 'Moorland running means peat, heather and bog. Footing is everything, so shorten your stride.' },
    { word: 'TAPE', fact: 'Breaking the finish tape is reserved for the winner. Kinesiology tape, the stretchy kind, is for everyone else.' },
    { word: 'KNEE', fact: "Runner's knee, a pain around the kneecap, often comes from weak hips. Strength work helps more than rest alone." },
    { word: 'GILL', fact: 'A gill, sometimes spelt ghyll, is a narrow ravine with a stream. Wordsworth helped make the ghyll spelling popular.' },
    { word: 'FUEL', fact: 'For events over two hours, aim for 60 to 90 g of carbohydrate an hour. Practise it in training, not on race day.' },
    { word: 'CLUB', fact: 'Running clubs in the UK go back to the 1860s. Most still welcome beginners, and the post-run cake is usually free.' },
    { word: 'PEAK', fact: 'Plans build to a peak week two or three weeks before the race, then taper. Fitness peaks after the training, not during.' },
    { word: 'SOCK', fact: 'Cotton socks hold water and cause blisters. Synthetic or merino wool socks wick sweat away.' },
    { word: 'TROT', fact: 'The Thanksgiving Turkey Trot is the most popular day of the year for races in America. Britain has its Christmas Day parkruns.', link: PARKRUN },
    { word: 'WIND', fact: "Running into a headwind costs more than a tailwind gives back. Tuck in behind another runner when you can." },
    { word: 'DALE', fact: 'Dale is an old word for valley. The Yorkshire Dales are home to the Three Peaks Race, first run in 1954.' },
    { word: 'EASY', fact: 'Most of your running should feel easy: able to talk in full sentences. Easy days make hard days possible.' },
    { word: 'CRAG', fact: 'A crag is a steep, rocky outcrop. On a fell race, the line round it is often faster than the line over it.' },
    { word: 'STEP', fact: 'Most runners take between 150 and 190 steps a minute. Shorter, quicker steps reduce the load on each landing.' },
    { word: 'TEAM', fact: 'Cross country is scored by team: add up your counters\' places and the lowest total wins. Every place matters.' },
    { word: 'HEEL', fact: 'Heel striking is not wrong in itself. What matters more is landing with your foot close under your body.' },
    { word: 'BEEP', fact: 'The bleep test, or multi-stage fitness test, was published in 1982. Every PE class in Britain has feared it since.' },
    { word: 'GATE', fact: 'On fell and trail races, leave every gate as you found it. A marshal may be watching, so will a farmer.' },
    { word: 'FOAM', fact: 'Light, springy foam in the Nike Vaporfly changed road racing from 2017. A foam roller is the cheaper foam in your house.', link: SHOES },
    { word: 'LANE', fact: 'In a 200 m or 400 m race, runners stay in their lanes, with staggered starts so everyone runs the same distance.' },
    { word: 'GRIT', fact: 'Gritstone edges of the Peak District give some of the best trail running in England, and the grippiest rock.' },
    { word: 'ACHE', fact: 'Muscle soreness that peaks a day or two after a hard run is normal. Sharp pain that gets worse as you run is not.' },
    { word: 'PACK', fact: 'Running in a pack saves energy, and the pack usually splits on the last climb. Know where that climb is.' },
    { word: 'FORD', fact: 'Rivers on fell races can rise fast after rain. Organisers can and do change the route when a ford is unsafe.' },
    { word: 'BASE', fact: 'Base training is weeks of easy, steady mileage before any speedwork. It builds the engine the hard sessions rely on.' },
    { word: 'LEGS', fact: "Legs gone? Shorten your stride and keep your arms moving. Arms set the rhythm the legs follow." },
    { word: 'SNOW', fact: 'In snow, shoes with deep lugs or microspikes help. Run on the fresh snow beside trodden paths, it grips better.' },
    { word: 'ROAD', fact: 'Road races in the UK are measured by the shortest possible line, so your watch will almost always say a little more.' },
    { word: 'PLOD', fact: 'A slow plod still counts. Time on your feet builds endurance whatever the pace.' },
    { word: 'TIME', fact: 'Gun time starts when the race starts. Chip time starts when you cross the line. Records use gun time.' },
    { word: 'PATH', fact: 'A public right of way in England may be a footpath, bridleway or byway. Runners can use them all.' },
    { word: 'JOGS', fact: 'Jogging became a craze after Bill Bowerman co-wrote the book Jogging in 1966. He also co-founded Nike.' },
    { word: 'REPS', fact: 'Reps are the repeated efforts in a session, like 6 x 800 m. The recovery between them matters as much as the reps.' },
    { word: 'TORS', fact: 'Dartmoor has more than 160 tors, granite outcrops on the hilltops. The Ten Tors challenge for teenagers began in 1960.' },
    { word: 'OATS', fact: 'Porridge two or three hours before a long run is a classic British pre-race breakfast. Slow to digest, so leave time.' },
    { word: 'CHIP', fact: 'Most timing chips are on the back of the race number now. Pin the number on the front and leave the chip unbent.' },
    { word: 'DUNE', fact: 'The Marathon des Sables crosses about 250 km of the Sahara, dunes included. Gaiters keep the sand out of your shoes.' },
    { word: 'FORM', fact: 'Good running form looks relaxed: tall posture, loose shoulders, feet landing close under the body.' },
    { word: 'BURN', fact: 'Burn is the Scottish word for a stream. Hill races in Scotland often cross several.' },
    { word: 'CAKE', fact: 'Cake at the finish is a sacred tradition of British club and fell races. Some events are chosen for it.' },
    { word: 'SOLE', fact: 'The outsole is the rubber under a shoe. Road shoes wear there first, usually at the outside of the heel.', link: SHOES },
    { word: 'GLEN', fact: 'A glen is a Scottish valley, usually long and narrow. The Glen Coe Skyline is one of Britain\'s toughest mountain races.' },
    { word: 'PINS', fact: 'Four safety pins, one in each corner, keep a race number flat. Most races hand them out with the number.' },
    { word: 'MIST', fact: 'When the mist comes down on the hills, slow down and check the map more often. Paths look different in cloud.' },
    { word: 'HIPS', fact: 'Weak hips let the knees drift inwards when you land. Side planks and clams help.' },
    { word: 'SOUP', fact: 'Hot soup at night aid stations has kept many ultra runners going. Salt, warmth and liquid in one cup.' },
    { word: 'LUGS', fact: 'Lugs are the studs on a trail shoe\'s sole. Deep, widely spaced lugs grip mud and shed it.', link: SHOES },
    { word: 'DAWN', fact: 'Dawn runs mean cooler air and quieter roads. Have something light to eat if the run is long.' },
    { word: 'ARMS', fact: 'Your arms set your rhythm. On a climb, drive them harder and your legs tend to follow.' },
    { word: 'COLA', fact: 'Flat cola is an ultra aid station favourite: quick sugar and a little caffeine, easy on a tired stomach.' },
    { word: 'EDGE', fact: 'Gritstone edges like Stanage in the Peak District give fast running with long views, and good grip even when wet.' },
    { word: 'TOES', fact: 'Leave about a thumb\'s width of space in front of your longest toe. Feet swell on long runs.', link: SHOES },
    { word: 'LOCH', fact: 'The Loch Ness Marathon starts in the hills south of the loch and finishes in Inverness.' },
    { word: 'SKIP', fact: 'A-skips and B-skips are running drills that train a quick, high knee lift. Most coaches use them in a warm-up.' },
    { word: 'BELT', fact: 'A race number belt saves pinning a number to your top. Triathletes use them to swap the number front to back.' },
    { word: 'HAGS', fact: 'Peat hags are eroded banks of peat on high moorland. Picking a line through them is a fell runner\'s art.' },
    { word: 'RAIN', fact: 'Running in the rain is rarely as bad as it looks from indoors. Tie your laces tighter, wet laces loosen.' },
    { word: 'VERT', fact: 'Vert is the climbing on a run, in metres. A vertical kilometre race climbs 1,000 m in a very short distance.' },
    { word: 'SAND', fact: 'Soft sand is hard work, firm sand by the water\'s edge is fast. Low tide is the beach runner\'s friend.' },
    { word: 'CORE', fact: 'A strong core keeps your body steady as your legs tire. A few minutes twice a week is enough to help.' },
    { word: 'RUNS', fact: 'Most good weeks of training are made of easy runs, with one or two harder ones. Variety keeps them interesting.' },
    { word: 'ARCH', fact: 'High or low arches change how your foot rolls. A shop with a treadmill can show you what yours does.', link: SHOES },
    { word: 'LOCK', fact: 'Canal locks are the only hills on a towpath run. Watch for wet stone and mooring ropes at the gates.' },
    { word: 'DUSK', fact: 'At dusk, drivers see runners late. Wear something bright or reflective once the light starts to fade.' },
    { word: 'FEED', fact: 'A feed station is where races hand out food and drink. Know what\'s on it before race day.' },
    { word: 'HOPS', fact: 'Hopping and bounding drills build spring in the calves and tendons. Start with a few and build up slowly.' },
    { word: 'LAST', fact: 'A last is the foot-shaped mould a shoe is built around. It decides the shoe\'s shape more than anything else.', link: SHOES },
    { word: 'IRON', fact: 'Runners, especially women, can run low on iron. Unusual tiredness is worth a blood test from your doctor.' },
    { word: 'DASH', fact: 'Americans called the short sprint the 100-yard dash. Metric distances took over the track, but the word dash stuck.' },
    { word: 'SOLO', fact: 'Solo runs build the mental strength to keep going when the pack moves away on race day.' },
    { word: 'GOAL', fact: 'A goal that scares you a little is the right size. Write it down and tell someone.' },
    { word: 'FAST', fact: 'Running fast now and then keeps easy running feeling easy. Strides are the gentlest way in.' },
    { word: 'KERB', fact: 'Step off a kerb, not over the edge of it. Turned ankles on kerbs are a classic road-race injury.' },
    { word: 'LAMP', fact: 'Americans say headlamp, Britons say head torch. On a dark trail, the brighter the better.' },
    { word: 'FLAT', fact: 'A flat course is fast but hard on the legs, as the same muscles work every stride. Hills share the load.' },
    { word: 'TAIL', fact: 'Every parkrun has a tail walker, so nobody ever finishes last.', link: PARKRUN },
    { word: 'SLOW', fact: 'Easy runs should feel slow. Many runners run them too fast and arrive at the hard sessions tired.' },
    { word: 'PREP', fact: 'Race prep starts the night before: kit laid out, number pinned, breakfast decided.' },
    { word: 'RACE', fact: 'Racing too often leaves no time to train. Most runners do best with a few key races a year.' },
    { word: 'SNUG', fact: 'Running shoes should feel snug at the heel and roomy at the toes.', link: SHOES },
  ],
  5: [
    { word: 'TRAIL', fact: "Trail shoes have deeper lugs and a tougher upper than road shoes. On hard-packed trails, road shoes are often fine.", link: SHOES },
    { word: 'TAPER', fact: 'Most marathon plans taper for two to three weeks. You lose almost no fitness, and you arrive with fresh legs.' },
    { word: 'CAIRN', fact: 'A cairn is a pile of stones marking a summit or path, from the Gaelic carn. Add a stone if you like, never take one.' },
    { word: 'CHAFE', fact: 'Chafing is friction on skin made worse by sweat. Petroleum jelly or anti-chafe balm before a long run saves misery.' },
    { word: 'RELAY', fact: 'In relays, the baton must pass inside the changeover zone. Drop it and the race usually goes with it.' },
    { word: 'TEMPO', fact: 'A tempo run is comfortably hard: you could speak a few words, not a sentence. Usually 20 to 40 minutes.' },
    { word: 'SCREE', fact: 'Scree is loose rock on a slope. Descending it well is a fell running skill: keep your weight forward and move your feet fast.' },
    { word: 'PACER', fact: 'Pacers in big marathons carry flags or balloons with a finish time. Stick with them early, decide later.' },
    { word: 'ULTRA', fact: 'An ultramarathon is any distance beyond the marathon\'s 42.195 km. The most common distances are 50 km, 50 miles, 100 km and 100 miles.' },
    { word: 'SPLIT', fact: 'A negative split means running the second half faster than the first. Most world records are run this way or close to it.', link: CALC },
    { word: 'STILE', fact: 'A stile lets walkers over a wall or fence. In a race, the queue at the first stile can cost more time than the hills.' },
    { word: 'CRAMP', fact: 'The cause of exercise cramp is still argued over. Fatigue seems to matter more than salt, so pace well.' },
    { word: 'RIDGE', fact: 'Ridge running is as exposed as it is beautiful. In cloud or high winds, the lower path is often the better choice.' },
    { word: 'MEDAL', fact: 'Some runners keep every medal. Others give them away. Either way, they are the only things you can\'t buy at the expo.' },
    { word: 'TOKYO', fact: 'Tokyo joined the World Marathon Majors in 2013. Its course finishes near Tokyo Station.' },
    { word: 'SWEAT', fact: 'Runners can lose anything from half a litre to two litres of sweat an hour. Weighing yourself before and after a run tells you yours.' },
    { word: 'CLIMB', fact: 'On steep climbs, power hiking with hands on thighs is often as fast as running, and much cheaper.' },
    { word: 'TRACK', fact: 'Track sessions are great for pace judgement: every 100 m is marked, so you can\'t kid yourself.' },
    { word: 'BOTHY', fact: 'A bothy is a simple mountain shelter, free to use. The Mountain Bothies Association looks after about 100 in Britain.' },
    { word: 'QUADS', fact: 'Long descents wreck the quads because the muscle works while lengthening. Train downhill before a hilly race.' },
    { word: 'SPIKE', fact: 'Track spikes screw in from below. Cross country spikes are longer, often 12 to 15 mm on deep mud.' },
    { word: 'START', fact: 'The start line is the most dangerous place in a race for your plan. Everyone feels fresh and everyone goes too fast.' },
    { word: 'TORCH', fact: 'Night sections of ultras need a head torch and spare batteries. Most races list both as compulsory kit.' },
    { word: 'LUNGS', fact: "Breathless on easy runs? Slow down. Easy should feel easy for your lungs and your legs." },
    { word: 'ROUND', fact: 'The Bob Graham Round links 42 Lakeland peaks in under 24 hours. Bob Graham set it in 1932.' },
    { word: 'WATER', fact: 'Drinking to thirst is enough for most races. Drinking far more than you sweat can be dangerous.' },
    { word: 'SURGE', fact: 'A surge is a sudden change of pace to break the group. Responding costs energy too, so choose which ones to cover.' },
    { word: 'CROSS', fact: 'The English National Cross Country Championships date back to the 1870s. Mud has been involved since the start.' },
    { word: 'HEART', fact: 'Resting heart rate falls as you get fitter. A sudden rise in the morning can be an early sign of illness or tiredness.' },
    { word: 'POLES', fact: 'Poles help on long climbs in mountain ultras. Some races ban them, so check the rules before you pack.' },
    { word: 'ANKLE', fact: 'Single-leg balance work strengthens ankles for rough ground. Stand on one leg while you brush your teeth.' },
    { word: 'QUEUE', fact: 'The toilet queue at a big marathon start can take longer than the first mile. Get there early.' },
    { word: 'LACES', fact: 'Double knot your laces before a race. Stopping to retie them costs far more than the extra few seconds.' },
    { word: 'MUDDY', fact: 'On a muddy course, short steps and a high cadence keep you upright. Long strides end in the mud.' },
    { word: 'STEEP', fact: 'On very steep ground, short steps uphill and quick feet downhill beat any heroic effort.' },
    { word: 'CARBS', fact: 'Carbohydrate loading works best over two or three days before a long race, not in one big pasta meal the night before.' },
    { word: 'FLASK', fact: 'Soft flasks shrink as you drink, so they don\'t slosh. Most trail vests carry two at the front.' },
    { word: 'LAYER', fact: 'Dress for the second mile, not the first. If you\'re warm at the start, you\'re overdressed.' },
    { word: 'SPEED', fact: 'Speedwork is a small part of most good training plans, often 10 to 20 percent. The rest is easy running.' },
    { word: 'RIVER', fact: 'The Thames Path follows the river for 184 miles from its source in the Cotswolds to the Thames Barrier.' },
    { word: 'ELITE', fact: 'Elite athletes start at the front of big marathons and have their own drinks tables, with their bottles marked.' },
    { word: 'DRINK', fact: 'At a drinks station, pinch the top of the paper cup into a spout. You\'ll drink more and wear less.' },
    { word: 'SOCKS', fact: 'Toe socks stop toes rubbing against each other. Runners either swear by them or have never tried them.' },
    { word: 'GLUTE', fact: 'Strong glutes keep your hips level as you land. Weak ones are behind many knee and hip niggles.' },
    { word: 'STONE', fact: 'UTMB Running Stones are earned at UTMB World Series races and give entry to the Mont-Blanc lottery.', link: { label: 'StoneTracker', href: '/tools/stone-tracker' } },
    { word: 'DIARY', fact: 'A training diary shows you what worked. Note how you felt as well as how far you ran.' },
    { word: 'HILLY', fact: 'On a hilly course, run to effort, not pace. Your watch will lie to you on the climbs and the descents.' },
    { word: 'SLEEP', fact: 'Sleep is when training turns into fitness. The night before the night before a race matters most.' },
    { word: 'WATCH', fact: 'GPS watches lose accuracy among tall buildings and under trees. Trust the mile markers over your wrist.' },
    { word: 'JELLY', fact: 'Jelly babies have fuelled British runners for decades. The aid station bowl is a national institution.' },
    { word: 'MARSH', fact: 'Crossing boggy ground, step on tufts of grass and heather. Bright green moss usually means deep water.' },
    { word: 'PASTA', fact: 'Pasta parties the night before a marathon are a tradition. Eat what you know, not a giant plate of something new.' },
    { word: 'GLOVE', fact: 'Cold hands slow you more than you think. Thin gloves weigh almost nothing and fit in any pocket.' },
    { word: 'BOGGY', fact: 'Bog trotters say the shortest line across a moor is rarely the driest. Local knowledge is worth minutes.' },
    { word: 'LYCRA', fact: 'Lycra, or elastane, was invented by DuPont in 1958. Running fashion has never fully recovered.' },
    { word: 'STRAP', fact: 'Chest strap heart rate monitors are more accurate than wrist sensors, especially in intervals.' },
    { word: 'FROST', fact: 'On frosty mornings, the grass verge often grips better than icy tarmac. Shorten your stride on slippery ground.' },
    { word: 'VISOR', fact: 'A visor shades your eyes while letting heat escape from the top of your head. Popular in hot races.' },
    { word: 'PLANK', fact: 'Planks build core strength without any kit. Thirty seconds done well beats two minutes done badly.' },
    { word: 'CHALK', fact: 'Chalk paths on the South Downs are fast when dry and like ice when wet. Grippy shoes earn their keep.' },
    { word: 'TREAD', fact: 'A shoe\'s tread wears faster than its foam on rough roads. Smooth patches mean less grip in the wet.', link: SHOES },
    { word: 'COAST', fact: 'The South West Coast Path runs 630 miles round the south-west peninsula. It has more climbing than many mountain races.' },
    { word: 'SWEEP', fact: 'Sweepers run at the back of trail and ultra races, collecting markers and checking on the last runners.' },
    { word: 'FLATS', fact: 'Racing flats were the light, thin shoes runners raced in for decades. Thick-foam racers have mostly replaced them.', link: SHOES },
    { word: 'HEATH', fact: 'Heathland means sandy paths, heather and gorse. Fast running, but watch for roots.' },
    { word: 'PULSE', fact: 'Take your pulse at the wrist or the neck for 15 seconds and multiply by four. Do it first thing in the morning.' },
    { word: 'BATON', fact: 'Relay batons are hollow tubes about 30 cm long. Races are lost at the changeover more often than on the bends.' },
    { word: 'GORSE', fact: 'Gorse flowers almost all year round. The old saying goes: when gorse is out of blossom, kissing\'s out of fashion.' },
    { word: 'THIGH', fact: 'Your thigh muscles take the brunt of a long descent. Train downhill before a hilly race.' },
    { word: 'CROWD', fact: 'Big-city marathon crowds can carry you for miles. Write your name on your vest and enjoy it.' },
    { word: 'FLINT', fact: 'Flints poke out of chalk paths on the Downs. Lift your feet, they trip the tired.' },
    { word: 'ROUTE', fact: 'Recce the route before a trail race if you can. Knowing the next climb is worth minutes.' },
    { word: 'SUGAR', fact: 'Sugar is the fastest fuel during a race. Gels, sweets and sports drinks all deliver it.' },
    { word: 'FIELD', fact: 'A race\'s field is everyone in it. A big field means you\'ll always have someone to run with.' },
    { word: 'ARROW', fact: 'Trail races mark the route with arrows, tape or flags. Look up at every junction.' },
    { word: 'CLIFF', fact: 'Coastal paths run close to cliff edges. In wind or fog, keep well inland of the edge.' },
    { word: 'SQUAD', fact: 'Training with a squad makes hard sessions easier. Someone is always there to chase.' },
    { word: 'TOAST', fact: 'Toast with honey or jam is a simple pre-race breakfast. Easy to digest and easy to find on race morning.' },
    { word: 'HEATS', fact: 'Track championships run heats to cut the field down to a final. Running the minimum to qualify is an art.' },
    { word: 'WOODS', fact: 'Running in woods is kinder on the legs and the mind. Studies link time among trees with lower stress.' },
    { word: 'BLOCK', fact: 'A training block is a few weeks with one focus, like speed or hills. Then rest and start the next.' },
    { word: 'CHEER', fact: 'A cheer from a stranger can lift your pace for a mile. Return the favour when you\'re spectating.' },
    { word: 'RIVAL', fact: 'A friendly rival is the best training partner. Every parkrun has one waiting to be found.', link: PARKRUN },
    { word: 'BEACH', fact: 'Beach running is good for strength and kind on the joints. Start on firm sand near the water.' },
    { word: 'COACH', fact: 'A good coach sees what you can\'t: when to push and when to rest.' },
    { word: 'HONEY', fact: 'Honey is mostly glucose and fructose, the same sugars many gels mix. Some gels are made with it.' },
    { word: 'CANAL', fact: 'Canal towpaths are flat, traffic-free and easy to follow. Perfect for a steady long run.' },
    { word: 'TITLE', fact: 'National titles in British running are decided at championship races. Club runners can enter many of them.' },
    { word: 'FLAGS', fact: 'Mountain races often mark the course with flags. In cloud, you run from one flag to the next.' },
    { word: 'DATES', fact: 'Dates are natural energy chews: sweet, soft and easy to carry. Many ultra runners swear by them.' },
    { word: 'CHASE', fact: 'Chasing the runner ahead is one of the easiest ways to run faster. Pick them off one by one.' },
    { word: 'BRISK', fact: 'A brisk walk is part of many ultra runners\' plans, especially on the climbs. It isn\'t giving up.' },
    { word: 'MILES', fact: 'A mile is 1,609.344 m. British road signs still use them, and so do most British runners.' },
    { word: 'FINAL', fact: 'A track final is often tactical, with a slow early pace and a fast finish. Heats are often quicker.' },
    { word: 'ROCKY', fact: 'On rocky ground, look two or three steps ahead, not at your feet. Your feet will find their way.' },
    { word: 'SLATE', fact: 'Wet slate is slippery underfoot. The Lake District and Snowdonia have plenty of it.' },
    { word: 'CLOCK', fact: 'The race clock shows gun time. Your chip time starts when you cross the start line.' },
    { word: 'STAGE', fact: 'Stage races split a long distance over several days, each with its own finish. The Marathon des Sables is one.' },
    { word: 'PRIZE', fact: 'Many smaller races give prizes by age category. Check the results, you may have won something.' },
    { word: 'PLANS', fact: 'A training plan works best when it fits your life. Move sessions around rather than skipping them.' },
    { word: 'BENDS', fact: 'More than half of a 400 m lap is run on the bends. Run them close to the inside of your lane.' },
    { word: 'ELBOW', fact: 'Keep your elbows bent at roughly 90 degrees and swing from the shoulder. Arms crossing the body waste energy.' },
    { word: 'TRAIN', fact: 'Train for the race you\'ve entered. A hilly ultra needs hills, a flat marathon needs steady miles.' },
    { word: 'GRASS', fact: 'Grass is softer than tarmac but less even. Cross country runners know every lump of it.' },
  ],
  6: [
    { word: 'STRIDE', fact: 'Strides are short, relaxed accelerations of about 20 seconds. A few after an easy run sharpen your form.' },
    { word: 'BOSTON', fact: 'The Boston Marathon was first run in 1897, the year after the first Olympic marathon. It is the oldest annual marathon in the world.', link: NEWS },
    { word: 'NIGGLE', fact: 'A niggle is the small ache before an injury. Two easy days now can save two months later.' },
    { word: 'CAMBER', fact: 'Roads slope away from the middle to drain water. Running the same side every day loads one leg more.' },
    { word: 'BUCKLE', fact: 'Western States finishers get a belt buckle: silver for under 24 hours, bronze for everyone else inside the 30-hour cut-off.' },
    { word: 'SPRINT', fact: 'The fastest humans reach their top speed around 60 m into a 100 m race. Nobody accelerates all the way.' },
    { word: 'GAITER', fact: 'Trail gaiters keep stones and grit out of your shoes. On a dusty course they save your feet.' },
    { word: 'TARTAN', fact: 'Tartan was the trade name of the first all-weather synthetic tracks. The 1968 Mexico City Olympics were the first to use one.' },
    { word: 'SUMMIT', fact: 'In mountain races, the summit is rarely the halfway point in time. The descent is where races are won and lost.' },
    { word: 'BALLOT', fact: 'Hundreds of thousands of people enter the London Marathon ballot every year. Most are unlucky, and try again next year.', link: NEWS },
    { word: 'TENDON', fact: 'The Achilles is the strongest tendon in the body. Heavy, slow calf raises are the standard rehab for it.' },
    { word: 'CINDER', fact: 'Before synthetic tracks, races were run on cinders. Bannister\'s four-minute mile was run on a cinder track.' },
    { word: 'PODIUM', fact: 'Age-group podiums make many runners\' seasons. Turn up to the prize giving, they do call the names.' },
    { word: 'SPARTA', fact: 'The Spartathlon runs 246 km from Athens to Sparta, ending when runners touch the foot of the statue of King Leonidas.', link: NEWS },
    { word: 'THIRST', fact: 'For most runners in most races, thirst is a good guide to how much to drink.' },
    { word: 'MIDGES', fact: 'Scottish midges are worst from late May to September, on still, damp evenings. Keep moving.' },
    { word: 'SPLITS', fact: 'Even splits are usually the fastest way to run any distance from 5 km up.', link: CALC },
    { word: 'CUTOFF', fact: 'Ultras set cut-off times at checkpoints. Missing one usually ends your race, so know them before you start.' },
    { word: 'BERLIN', fact: 'Berlin\'s flat, fast course has seen more men\'s marathon world records than any other.', link: NEWS },
    { word: 'INSOLE', fact: 'The insole that comes with your shoe can be swapped. Take your orthotics shoe shopping.', link: SHOES },
    { word: 'PUDDLE', fact: 'In a trail race, going round a puddle widens the path and wrecks the verge. Go straight through.' },
    { word: 'ASCENT', fact: 'Naismith\'s rule, written for walkers in 1892, adds an hour for every 600 m of climbing. Runners pay a similar price.' },
    { word: 'TIMING', fact: 'Most race timing chips use radio frequency. Mats at the start and finish read them as you cross.' },
    { word: 'PHYSIO', fact: 'See a physio about pain that changes how you run. Limping on is how a niggle turns into a stress fracture.' },
    { word: 'LONDON', fact: 'The first London Marathon was run in 1981. It calls itself the largest annual one-day fundraising event in the world.', link: NEWS },
    { word: 'VALLEY', fact: 'Valley bottoms are colder than slopes on clear nights, as cold air sinks. Pack a layer for the low checkpoints.' },
    { word: 'BEANIE', fact: 'A thin hat on a cold day lets you dress lighter elsewhere. Take it off when you warm up.' },
    { word: 'OXYGEN', fact: 'VO2 max is the most oxygen your body can use. It can rise with training, but it isn\'t the only thing that decides your race.' },
    { word: 'JACKET', fact: 'Fell races often require a waterproof jacket with taped seams. A windproof doesn\'t count.' },
    { word: 'UPHILL', fact: 'Uphill running is speedwork in disguise. Your heart rate rises without the pounding of fast running on the flat.' },
    { word: 'TROPHY', fact: 'Many club trophies are older than the members racing for them. Check the names engraved on the base.' },
    { word: 'NETTLE', fact: 'Nettles sting through thin tights. Trail runners in shorts learn the dock leaf cure early.' },
    { word: 'PACING', fact: 'Pacing is the most underrated skill in running. It costs nothing and is worth minutes.', link: CALC },
    { word: 'SODIUM', fact: 'Sweat is salty because it carries sodium. Salty sweaters see white marks on their kit after a long run.' },
    { word: 'BRIDGE', fact: 'Glute bridges are among the simplest strength exercises for runners. No gym needed.' },
    { word: 'RUNNER', fact: 'All you need to be a runner is a pair of shoes and a door. That\'s why so many of us are.' },
    { word: 'FOREST', fact: 'Forest trails are kinder to the legs than tarmac. Roots and leaves hide trip hazards, so lift your feet.' },
    { word: 'TOILET', fact: 'Every runner has a toilet story. Trail etiquette: well away from water and paths, and take your paper with you.' },
    { word: 'SHORTS', fact: 'Split shorts give the most freedom of movement. Pockets for gels are the modern upgrade.' },
    { word: 'COFFEE', fact: 'Caffeine is one of the few legal aids with good evidence for endurance. Try it in training before race day.' },
    { word: 'STEADY', fact: 'A steady run sits between easy and tempo. Many runners run all their miles here by accident.' },
    { word: 'BANANA', fact: 'A banana carries about 25 g of carbohydrate. Nature\'s energy gel, in its own wrapper.' },
    { word: 'TIGHTS', fact: 'Compression tights claim to reduce muscle vibration. The evidence is mixed, but they keep your legs warm.' },
    { word: 'INJURY', fact: 'Most running injuries come from doing too much, too soon. Increase weekly mileage gradually.' },
    { word: 'STREAM', fact: 'In the hills, streams look clean but may not be. Filter bottles are cheap and light.' },
    { word: 'ROLLER', fact: 'Foam rolling feels good and may help you move better. It won\'t fix a real injury.' },
    { word: 'NUMBER', fact: 'Writing your name on your race number gets you cheered by strangers all the way round.' },
    { word: 'RACING', fact: 'Racing teaches what training can\'t. A few low-key races before your goal race are worth the entry fee.' },
    { word: 'JUNIOR', fact: 'Junior parkrun is 2 km, for children aged 4 to 14, on Sunday mornings.', link: PARKRUN },
    { word: 'MEDALS', fact: 'At the Olympics, gold medals are mostly silver, with a thin plating of gold.' },
    { word: 'GRAVEL', fact: 'Gravel paths are fast and forgiving. Loose gravel on a descent is not, so shorten your stride.' },
    { word: 'AUTUMN', fact: 'Autumn is marathon season: Berlin, Chicago and New York all fall between late September and early November.', link: NEWS },
    { word: 'SPONGE', fact: 'Some big races hand out sponges on hot days. Squeeze the water over your head, not into your shoes.' },
    { word: 'TARMAC', fact: 'Tarmac is harder than trail but more even underfoot. Your legs adapt to whatever surface you train on most.' },
    { word: 'WINTER', fact: 'Winter training builds spring PBs. Dark mornings need a light and something reflective.' },
    { word: 'ENERGY', fact: 'The energy drink at aid stations is often a different brand from the one you trained with. Check before race day.' },
    { word: 'CALVES', fact: 'Your calves do huge work on every run. Slow, heavy calf raises make them stronger.' },
    { word: 'HURDLE', fact: 'Men\'s sprint hurdles are 110 m, women\'s 100 m. The 400 m hurdles is one of the hardest events on the track.' },
    { word: 'BRONZE', fact: 'Bronze medals go to third place. Some runners say third is the happiest place on a podium.' },
    { word: 'EFFORT', fact: 'Running by effort means listening to your body, not the watch. On hills and in heat, it\'s the better guide.' },
    { word: 'RHYTHM', fact: 'Find a rhythm on long runs and let it carry you. Breathing and footsteps often fall into step.' },
    { word: 'JOGGER', fact: 'Jogging and running are the same thing at different speeds. Nobody needs to apologise for their pace.' },
    { word: 'BOTTLE', fact: 'Bottles on the front of a running vest are easier to reach than one in the back. Practise filling them on the move.' },
    { word: 'ANORAK', fact: 'Anorak comes from an Inuit word for a hooded jacket. Fell runners call theirs a cag, short for cagoule.' },
    { word: 'RECORD', fact: 'Most course records are set in good weather on a good day. Few runners get both.' },
    { word: 'SEASON', fact: 'Cross country season runs through the winter, road racing peaks in spring and autumn.' },
    { word: 'LEAGUE', fact: 'Cross country leagues give club runners a race most winter Saturdays. Points count, every place matters.' },
    { word: 'COUNTY', fact: 'County championships are often the first step into proper competition. Anyone in a club can usually enter.' },
    { word: 'CANYON', fact: 'Canyon running means steep descents first and long climbs back. Pace the climb out, not the way in.' },
    { word: 'DESERT', fact: 'Desert races are hot by day and cold by night. Pack for both.' },
    { word: 'ARCTIC', fact: 'Arctic ultras are run on snow and ice in extreme cold. Kit decisions can be the difference between finishing and frostbite.' },
    { word: 'ALPINE', fact: 'Alpine races climb high enough for altitude to matter. Above about 2,500 m, most runners feel it.' },
    { word: 'ISLAND', fact: 'Island races mean sea views, wind and usually plenty of hills.' },
    { word: 'TUNNEL', fact: 'GPS watches lose signal in tunnels and often jump when they find it again. Trust the course markers.' },
    { word: 'STAIRS', fact: 'Stair running is an old training trick. Short, sharp and good for the legs, if hard on the lungs.' },
    { word: 'LADDER', fact: 'Agility ladder drills improve foot speed and coordination. Quick feet help on rough trails.' },
    { word: 'SPRING', fact: 'Spring is marathon season in Britain: London, Manchester, Brighton and more.' },
    { word: 'SUMMER', fact: 'In summer, run early or late. The middle of the day is for shade and a cold drink.' },
    { word: 'BREEZE', fact: 'A light breeze cools you down on a hot day. A strong one just slows you down.' },
    { word: 'FINISH', fact: 'Look up as you cross the finish line, the photographers are waiting. And stop your watch afterwards.' },
    { word: 'DOPING', fact: 'In athletics, doping cases are handled by the Athletics Integrity Unit, set up in 2017.', link: NEWS },
    { word: 'CHAMPS', fact: 'Championship races are run for places, not times. Tactics matter more than splits.' },
    { word: 'RUGGED', fact: 'Rugged trails reward strong ankles and good balance. Practise on them before race day.' },
    { word: 'REMOTE', fact: 'On remote runs, tell someone your route and when you\'ll be back. Carry a phone and a layer.' },
    { word: 'SAFETY', fact: 'Fell race kit lists are about safety, not fashion. Carry them even when the forecast is good.' },
    { word: 'RESCUE', fact: 'Mountain rescue teams in the UK are volunteers. Many runners donate to their local team.' },
    { word: 'SUNHAT', fact: 'A light cap or sunhat keeps the sun off and holds water when you pour some over your head.' },
    { word: 'BOUNCE', fact: 'A little bounce in your stride is efficient, too much wastes energy going up instead of forward.' },
    { word: 'SQUALL', fact: 'Squalls on the hills arrive fast. Waterproof on before you get cold, not after.' },
    { word: 'REWARD', fact: 'Plan a reward for after a big race. It\'s surprisingly good motivation at mile 20.' },
    { word: 'MORALE', fact: 'Low points come in every long race, and they pass. Eat something, then reassess.' },
    { word: 'PEBBLE', fact: 'A pebble in your shoe won\'t go away on its own. Stop and take it out.' },
    { word: 'GRITTY', fact: 'Gritty runners aren\'t always the most talented. They\'re the ones who keep showing up.' },
    { word: 'MEADOW', fact: 'Meadow paths are soft and pretty in summer, but long grass hides holes. Keep your eyes down.' },
    { word: 'SCENIC', fact: 'Scenic routes make long runs go faster. Plan the long run of the week somewhere worth seeing.' },
    { word: 'MUSCLE', fact: 'Muscle is built during rest, not during the run. Easy days are where training turns into fitness.' },
    { word: 'KITBAG', fact: 'Pack your kitbag the night before a race. Spare socks and a warm layer for afterwards are never wasted.' },
    { word: 'SHADES', fact: 'Sunglasses reduce squinting and glare on bright days. Some runners say they help them relax.' },
    { word: 'RAVINE', fact: 'Steep ravines on trail races are often roped or marshalled. Go slowly, it\'s never worth a fall.' },
    { word: 'NIMBLE', fact: 'Nimble feet win descents. Practise short, quick steps on rough ground.' },
    { word: 'SILVER', fact: 'Silver for second. Many great runners have more silver medals than gold.' },
    { word: 'JUNGLE', fact: 'Jungle races are hot, humid and wet. Feet stay damp for days, so foot care is everything.' },
    { word: 'MENTOR', fact: 'Many clubs pair new runners with experienced ones. Ask, most runners love to help.' },
    { word: 'RESULT', fact: 'A result is more than a time. Placing, conditions and how you felt all count.' },
  ],
  7: [
    { word: 'FARTLEK', fact: 'Fartlek is Swedish for speed play. Gösta Holmér developed it in the 1930s: fast and slow running by feel, not by the watch.' },
    { word: 'PARKRUN', fact: 'parkrun began on 2 October 2004 at Bushy Park in south-west London, with 13 runners. Its name is always lower case.', link: PARKRUN },
    { word: 'BLISTER', fact: 'Blisters come from friction, heat and moisture. Treat a hot spot before it becomes a blister.' },
    { word: 'CADENCE', fact: 'The 180 steps a minute target comes from Jack Daniels counting elite runners\' steps at the 1984 Olympics. Your best cadence may differ.' },
    { word: 'CHICAGO', fact: 'Kelvin Kiptum set the men\'s marathon world record of 2:00:35 in Chicago in 2023. Ruth Chepngetich set the women\'s, 2:09:56, there in 2024.', link: NEWS },
    { word: 'HARRIER', fact: 'Many British clubs are called Harriers, after the hare and hounds paper chases that began club cross country in the 1800s.' },
    { word: 'TOWPATH', fact: 'Canal towpaths were built for horses pulling boats. They make flat, traffic-free running routes through towns and cities.' },
    { word: 'LACTATE', fact: 'Lactate doesn\'t cause next-day soreness. Your body uses it as fuel, and it clears within an hour of a hard session.' },
    { word: 'MARSHAL', fact: 'Marshals stand in the cold so you can race. Thank every one of them.' },
    { word: 'DESCENT', fact: 'Good descenders look ahead, not at their feet, and let gravity do the work. It takes practice.' },
    { word: 'TOENAIL', fact: 'Black toenails come from toes hitting the front of the shoe, often on descents. A half size up can help.', link: SHOES },
    { word: 'LOTTERY', fact: 'Western States, UTMB and Hardrock all use lotteries, as many more people want to race than there are places.' },
    { word: 'STRETCH', fact: 'Static stretching before a run doesn\'t prevent injury. Save it for afterwards, and warm up by jogging.' },
    { word: 'COMPASS', fact: 'Fell races often require a map and compass as compulsory kit. Carrying one helps only if you can use it.' },
    { word: 'MIDSOLE', fact: 'The midsole is the foam between your foot and the road. It is where almost all the recent shoe innovation lives.', link: SHOES },
    { word: 'HAIRPIN', fact: 'On a zigzag path, cutting the corners erodes the hillside. Stick to the line, it is usually quicker anyway.' },
    { word: 'PROTEIN', fact: 'Protein after a hard run helps your muscles repair. A glass of milk does the job well.' },
    { word: 'BRAMBLE', fact: 'Bramble scratches are a sign of a proper trail run. Long socks are the trail runner\'s armour.' },
    { word: 'TRAINER', fact: 'In Britain we call running shoes trainers. In America, a trainer is a person who looks after athletes.' },
    { word: 'PLATEAU', fact: 'A training plateau often means you need more rest, not more training. Fitness is built during recovery.' },
    { word: 'HYDRATE', fact: 'You can\'t hydrate in advance by drinking far more than normal. Your kidneys just pass it straight on.' },
    { word: 'BEARING', fact: 'Taking a bearing means lining up the compass with the map, then following the arrow. Practise in clear weather first.' },
    { word: 'CUSHION', fact: 'More cushioning doesn\'t always mean fewer injuries. The best shoe is often simply the most comfortable one.', link: SHOES },
    { word: 'RECOVER', fact: 'A rough rule of thumb is one easy day for every mile raced. A marathon deserves a few weeks of gentle running.' },
    { word: 'POSTURE', fact: 'Run tall, with relaxed shoulders. When you tire, check your shoulders first, they creep up.' },
    { word: 'BREATHE', fact: 'Breathing through your mouth is fine when running hard. You need all the air you can get.' },
    { word: 'MASSAGE', fact: 'Sports massage helps many runners feel looser. Book it a few days before a race, not the day before.' },
    { word: 'SUNBURN', fact: 'Long runs mean hours in the sun. Sun cream on the back of the neck and the tops of the ears is easily forgotten.' },
    { word: 'STAGGER', fact: 'Staggered starts in lane races make everyone run the same distance. The outside lane only looks ahead.' },
    { word: 'WHISTLE', fact: 'Fell races often require a whistle in your kit. Six blasts, repeated each minute, is the mountain distress signal.' },
    { word: 'BLANKET', fact: 'A foil survival blanket weighs almost nothing and is on most mountain race kit lists.' },
    { word: 'HEATHER', fact: 'Heather looks soft but hides holes and stones. Running through it is slow, tiring work.' },
    { word: 'BRACKEN', fact: 'Bracken covers many British hillsides in summer. Check for ticks after running through it.' },
    { word: 'MILEAGE', fact: 'A common rule is to raise weekly mileage by no more than about 10 percent. Back off every third or fourth week.' },
    { word: 'STAMINA', fact: 'Stamina is built with time on your feet. Long, easy runs do most of the work.' },
    { word: 'WAYMARK', fact: 'Waymarks are small signs or arrows on posts showing a path. National Trails in England use an acorn.' },
    { word: 'GRANITE', fact: 'Granite gives grippy rock in the dry. Dartmoor\'s tors are made of it.' },
    { word: 'GLACIER', fact: 'Some mountain races cross glaciers, roped and guided. Most stay well below them.' },
    { word: 'HARBOUR', fact: 'Coastal races often start and finish at a harbour. Expect a sharp climb out of town.' },
    { word: 'THUNDER', fact: 'If you hear thunder in the hills, get off the tops and away from ridges. Races are stopped for it.' },
    { word: 'DRIZZLE', fact: 'Drizzle soaks through slowly. A light waterproof is worth carrying on long runs.' },
    { word: 'ATHLETE', fact: 'Every runner who pins on a number is an athlete. Elite or not.' },
    { word: 'PLASTER', fact: 'A plaster on a hot spot early saves a blister later. Carry a couple on long runs.' },
    { word: 'BANDAGE', fact: 'A small first-aid kit with a bandage is on many trail race kit lists. Hope you never need it.' },
    { word: 'THERMAL', fact: 'A thermal base layer is the best friend of a winter runner. Keep it close to the skin.' },
    { word: 'CAPTAIN', fact: 'Club captains organise teams for relays and leagues. Ask yours how to get into a team.' },
    { word: 'STARTER', fact: 'The race starter fires the gun or sounds the hooter. Elite races use electronic timing linked to it.' },
    { word: 'BLADDER', fact: 'A hydration bladder in a pack holds more than bottles. It\'s harder to see how much is left.' },
    { word: 'MITTENS', fact: 'Mittens are warmer than gloves because your fingers share their heat.' },
    { word: 'BOULDER', fact: 'Boulder fields slow everyone down. Step on the tops of the rocks, not the gaps.' },
    { word: 'HILLTOP', fact: 'Pause on a hilltop now and then. The view is part of the run.' },
    { word: 'WEEKEND', fact: 'The weekend long run is the backbone of most marathon plans. Protect it in your diary.' },
  ],
};
